project-id: lille-422512
project-name: lille 
cloud: gcp
credentials-path: C:\Repositorio\Python\p95-accelera360\scr\config\lille-422512-a12a0a3c757b.json
bucket-projeto: p95-accelera360
bucket-bronze: bronze
bucket-silver: silver
bucket-gold: gold
bucket-dw: dw